### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [0xpr03/clantool#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by 0xpr03** [comment]
No, as long as I can use [config.rs](https://github.com/0xpr03/clantool/blob/master/src/config.rs) in the way it's been until now to deserialize my config files, everything is fine. I guess the same applies to my yayd code.

#Edit:
I only liked having serialization inside the default library, rust applications really have such long dependency lists, that it can be a pain to upgrade these (speaking of yayd for example, upgrade conflicts between crates). But this is another topic.
